#define TAPPING_TERM 180
#define IGNORE_MOD_TAP_INTERRUPT

#define BOTH_SHIFTS_TURNS_ON_CAPS_WORD

#define MK_KINETIC_SPEED

#undef MOUSEKEY_INTERVAL
#define MOUSEKEY_INTERVAL 13

#undef MOUSEKEY_DELAY
#define MOUSEKEY_DELAY 5

#define MOUSEKEY_MOVE_DELTA 6
#define MOUSEKEY_INITIAL_SPEED 150
#define MOUSEKEY_BASE_SPEED 150
#define MOUSEKEY_ACCELERATED_SPEED 3000
#define MOUSEKEY_DECELERATED_SPEED 400

#undef MOUSEKEY_TIME_TO_MAX
#define MOUSEKEY_TIME_TO_MAX 50

#undef MOUSEKEY_MAX_SPEED
#define MOUSEKEY_MAX_SPEED 7

#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 0

#undef MOUSEKEY_WHEEL_INTERVAL
#define MOUSEKEY_WHEEL_INTERVAL MOUSEKEY_INTERVAL

#undef MOUSEKEY_WHEEL_MAX_SPEED
#define MOUSEKEY_WHEEL_MAX_SPEED MOUSEKEY_MAX_SPEED

#undef MOUSEKEY_WHEEL_TIME_TO_MAX
#define MOUSEKEY_WHEEL_TIME_TO_MAX MOUSEKEY_TIME_TO_MAX
